// src/components/icon.js

export const getIconUrl = (type) => {
    switch (type) {
      case 'alpine_hut':
        return '/alpinehut.png';
      case 'archaeological':
        return '/archeology.png';
      case 'arts_centre':
        return '/artcenter.png';
      case 'artwork':
        return '/artwork.png';
      case 'atm':
        return '/atm.png';
        case 'attraction':
            return '/attraction.png';
          case 'bakery':
            return '/bakery.png';
          case 'bank':
            return '/bank.png';
          case 'bar':
            return '/bar.png';
          case 'battlefield':
            return '/battlefield.png';
          case 'beauty_shop':
            return '/beautyshop.png';
          case 'beverages':
            return '/beverages.png';
          case 'bicycle_shop':
            return '/bicycleshop.png';
          case 'bookshop':
            return '/bookstore.png';
          case 'butcher':
            return '/butcher.png';
          case 'cafe':
            return '/cafe.png';
          case 'camp_site':
            return '/campsite.png';
          case 'car_dealership':
            return '/cardealership.png';
          case 'car_wash':
            return '/carwash.png';
          case 'castle':
            return '/castle.png';
          case 'chemist':
            return '/chemist.png';
          case 'cinema':
            return '/cinema.png';
          case 'clinic':
            return '/clinic.png';
          case 'clothes':
            return '/clothes.png';
          case 'college':
            return '/college.png';
          case 'community_centre':
            return '/community_centre.png';
          case 'computer_shop':
            return '/computer.png';
          case 'convenience':
            return '/convenience_store.png';
          case 'courthouse':
            return '/court_house.png';
          case 'dentist':
            return '/dentist.png';
          case 'department_store':
            return '/departmentstore.png';
          case 'doctors':
            return '/doctor.jpeg';
          case 'doityourself':
            return '/doityourself.png';
          case 'drinking_water':
            return '/drinking_water.png';
          case 'embassy':
            return '/embassy.png';
          case 'fast_food':
            return '/fast_food.png';
          case 'fire_station':
            return '/fire_station.png';
          case 'florist':
            return '/florist.png';
          case 'food_court':
            return '/food_court.png';
          case 'fort':
            return '/fort.png';
          case 'fountain':
            return '/fountain.png';
          case 'furniture_shop':
            return '/furniture.png';
          case 'garden_centre':
            return '/gardening.png';
          case 'general':
            return '/general_store.png';
          case 'gift_shop':
            return '/gift.png';
          case 'golf_course':
            return '/golf.png';
          case 'graveyard':
            return '/graveyard.png';
          case 'greengrocer':
            return '/greengrocer.png';
          case 'guesthouse':
            return '/guesthouse.png';
          case 'hairdresser':
            return '/hairdresser.png';
          case 'hospital':
            return '/hospital.png';
          case 'hostel':
            return '/hostel.png';
          case 'hotel':
            return '/hotel.png';
          case 'jeweller':
            return '/jewelry.png';
          case 'kindergarten':
            return '/kindergarden.png';
          case 'laundry':
            return '/laundry.png';
          case 'library':
            return '/library.png';
          case 'mall':
            return '/mall.png';
          case 'market_place':
            return '/market_place.png';
          case 'memorial':
            return '/memorial.png';
          case 'mobile_phone_shop':
            return '/mobile_phone_shop.png';
          case 'monument':
            return '/monument.png';
          case 'motel':
            return '/motel.png';
          case 'museum':
            return '/museum.png';
          case 'nightclub':
            return '/night_club.png';
          case 'optician':
            return '/optician.png';
          case 'park':
            return '/park.png';
          case 'pharmacy':
            return '/pharmacy.png';
          case 'picnic_site':
            return '/picnic_site.png';
          case 'pitch':
            return '/pitch.png';
          case 'playground':
            return '/playground.png';
          case 'police':
            return '/police.png';
          case 'post_box':
            return '/post_box.png';
          case 'post_office':
            return '/post_office.png';
          case 'prison':
            return '/prison.png';
          case 'restaurant':
            return '/restaurant.png';
          case 'ruins':
            return '/ruins.png';
          case 'school':
            return '/school.png';
          case 'shelter':
            return '/shelter.png';
          case 'shoe_shop':
            return '/shoe_shop.png';
          case 'sports_centre':
            return '/sports_centre.png';
          case 'sports_shop':
            return '/sports_shop.png';
          case 'stadium':
            return '/stadium.png';
          case 'stationery':
            return '/stationary.png';
          case 'supermarket':
            return '/supermarket.png';
          case 'swimming_pool':
            return '/swimming_pool.png';
          case 'theatre':
            return '/theater.png';
          case 'theme_park':
            return '/theme_park.png';
          case 'tourist_info':
            return '/tourist_info.jpeg';
          case 'tower':
            return '/tower.png';
          case 'town_hall':
            return '/town_hall.jpeg';
          case 'toy_shop':
            return '/toy_shop.jpeg';
          case 'travel_agent':
            return '/travel_agent.jpeg';
          case 'university':
            return '/university.jpeg';
          case 'veterinary':
            return '/veterinary.jpeg';
          case 'viewpoint':
            return '/viewpoint.jpeg';
         
          case 'water_tower':
            return '/watertower.jpeg';
          case 'wayside_shrine':
            return '/wayside_shrine.jpeg';
          case 'zoo':
            return '/zoo.jpeg';
      default:
        return '/icons/default.png';
    }
  };
  